[alias]
xtask = "run --package xtask --"

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-Wl,-rpath,@executable_path/../python-dev/python/lib"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-Wl,-rpath,@executable_path/../python-dev/python/lib"]
